### ISSUE TITLE
Not working for .asm file extension

### ISSUE THREAD

**Issue by mreale** [DonaldHays/rgbds-vscode#7] opened 2019-10-23 04:21 UTC
I instaled the last version on VSCode and the extension stops being activated for **.asm** source files after I close/reopen the source folder.  It works consistently with **.sm83** extension, though.

Any ideas?

**Comment by DonaldHays** [comment] 2019-10-23 04:26
@mreale just tried poking around a bit with ASM files and opening and closing and it seems to still work.

Is it possible you've added another extension that associates with ASM files?

If not, could you try offering me a specific set of steps you can follow to consistently get this behavior that I can try to reproduce the issue?

**Comment by mreale** [comment] 2019-10-23 04:38
@DonaldHays, thank you for your reply.   I use a few plugins like Microsoft Intellicode, Microsoft C/C++ Intellisense and PlatformIO.  The steps I followed to reproduce the problem:

1) Close all folders
2) Install the RGBDS Z80 extension (version 2.4.1)
3) Open my folder with z80 **.asm** source files.  It works like a charm but....
4) After closing and reopening the aforementioned folder the extension stops to activate the syntax highlight - but it works great if I rename it to **.sm83**

I think you are right about another other plugin possibly using the .asm extension.  

Best regards

**Comment by DonaldHays** [comment] 2019-10-23 04:51
@mreale Looks like PlatformIO provides something for `asm` files.

You can configure your settings (either your global vscode `settings.json` or `.vscode/settings.json` in your project folder) to select one provider for specific file extensions using the `files.associations` key, like so:

```
{
  "files.associations": {
    "*.asm": "gbz80"
  }
}
```

Alternatively, I think you should be able to make this configuration using the UI. Open an ASM file, and on the bottom status bar in the lower right between the line ending mode and the "provide feedback" smiley emoji there's an indication of the language mode it's in. Click it and you'll get a prompt that will let you configure file associations.

Does messing around with that sort of configuration solve the problem?

**Comment by mreale** [comment] 2019-10-23 05:07
It's done!

Thanks for your valuable help @DonaldHays, very appreciated. I think I will enjoy using the RGBDS Z80 in my retro computing projects, it's a great tool.

Issue closed.

**Comment by DonaldHays** [comment] 2019-10-23 05:08
Awesome! Glad to hear it!

**Closed** 2019-10-23 05:07 UTC
